# this corresponds to the default config
train:
  dataset_path: BRCA_kd:root=/home/Daejeon/dataset/features/tcga_brca/prov_gigapath/s1_patchToken_regional/ 
  split_dir: '/home/Daejeon/jingwei/tcga_brca/tcga_brca_survival.csv'
  batch_size_per_gpu: 1
  patch_num: 256
student:
  arch: vit_small
  block_chunks: 4
  patch_num: 256

