# this corresponds to the default config
train:
  dataset_path: PITDataset:root=/home/Daejeon/sk_n_wei/vit_small_5organs_feat_49999_s1_agg/
  split_dir: '/home/Daejeon/jingwei/5organ_split.csv'
  batch_size_per_gpu: 64
  patch_num: 273
student:
  arch: vit_giant2
  block_chunks: 4
  patch_num: 273